# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StageCalibration.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StageCalibration(object):
    def setupUi(self, StageCalibration):
        StageCalibration.setObjectName("StageCalibration")
        StageCalibration.resize(570, 514)
        self.centralwidget = QtWidgets.QWidget(StageCalibration)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.executeText = QtWidgets.QLineEdit(self.centralwidget)
        self.executeText.setObjectName("executeText")
        self.horizontalLayout_3.addWidget(self.executeText)
        self.executePushButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.executePushButtonWidget.setObjectName("executePushButtonWidget")
        self.horizontalLayout_3.addWidget(self.executePushButtonWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 6, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.lowWavelengthSpinBoxWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lowWavelengthSpinBoxWidget.setMinimum(1.0)
        self.lowWavelengthSpinBoxWidget.setMaximum(9999.0)
        self.lowWavelengthSpinBoxWidget.setProperty("value", 600.0)
        self.lowWavelengthSpinBoxWidget.setObjectName("lowWavelengthSpinBoxWidget")
        self.gridLayout_2.addWidget(self.lowWavelengthSpinBoxWidget, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 2, 1, 1)
        self.pumpWavelengthSpinBoxWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pumpWavelengthSpinBoxWidget.setMinimum(1.0)
        self.pumpWavelengthSpinBoxWidget.setMaximum(9999.0)
        self.pumpWavelengthSpinBoxWidget.setProperty("value", 800.0)
        self.pumpWavelengthSpinBoxWidget.setObjectName("pumpWavelengthSpinBoxWidget")
        self.gridLayout_2.addWidget(self.pumpWavelengthSpinBoxWidget, 1, 1, 1, 1)
        self.guiCanvas = QtWidgets.QGridLayout()
        self.guiCanvas.setObjectName("guiCanvas")
        self.gridLayout_2.addLayout(self.guiCanvas, 4, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveFileButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.saveFileButtonWidget.setObjectName("saveFileButtonWidget")
        self.horizontalLayout_2.addWidget(self.saveFileButtonWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 8, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        self.higherStageSpinBoxWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.higherStageSpinBoxWidget.setMinimum(1.0)
        self.higherStageSpinBoxWidget.setMaximum(9999.0)
        self.higherStageSpinBoxWidget.setProperty("value", 85.0)
        self.higherStageSpinBoxWidget.setObjectName("higherStageSpinBoxWidget")
        self.gridLayout_2.addWidget(self.higherStageSpinBoxWidget, 3, 3, 1, 1)
        self.undoButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.undoButtonWidget.setObjectName("undoButtonWidget")
        self.gridLayout_2.addWidget(self.undoButtonWidget, 1, 2, 1, 1)
        self.lowerStageSpinBoxWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lowerStageSpinBoxWidget.setMinimum(1.0)
        self.lowerStageSpinBoxWidget.setMaximum(9999.0)
        self.lowerStageSpinBoxWidget.setProperty("value", 81.0)
        self.lowerStageSpinBoxWidget.setObjectName("lowerStageSpinBoxWidget")
        self.gridLayout_2.addWidget(self.lowerStageSpinBoxWidget, 3, 1, 1, 1)
        self.highWavelengthSpinBoxWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.highWavelengthSpinBoxWidget.setMinimum(1.0)
        self.highWavelengthSpinBoxWidget.setMaximum(9999.0)
        self.highWavelengthSpinBoxWidget.setProperty("value", 800.0)
        self.highWavelengthSpinBoxWidget.setObjectName("highWavelengthSpinBoxWidget")
        self.gridLayout_2.addWidget(self.highWavelengthSpinBoxWidget, 2, 3, 1, 1)
        self.loadFileButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.loadFileButtonWidget.setObjectName("loadFileButtonWidget")
        self.gridLayout_2.addWidget(self.loadFileButtonWidget, 0, 0, 1, 3)
        self.formulaWidget = QtWidgets.QLabel(self.centralwidget)
        self.formulaWidget.setObjectName("formulaWidget")
        self.gridLayout_2.addWidget(self.formulaWidget, 5, 0, 1, 4)
        self.saveFileDefaultButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.saveFileDefaultButtonWidget.setObjectName("saveFileDefaultButtonWidget")
        self.gridLayout_2.addWidget(self.saveFileDefaultButtonWidget, 8, 3, 1, 1)
        self.gridLayout_2.setRowStretch(0, 3)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 1)
        self.gridLayout_2.setRowStretch(4, 20)
        StageCalibration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StageCalibration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 21))
        self.menubar.setObjectName("menubar")
        StageCalibration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StageCalibration)
        self.statusbar.setObjectName("statusbar")
        StageCalibration.setStatusBar(self.statusbar)

        self.retranslateUi(StageCalibration)
        QtCore.QMetaObject.connectSlotsByName(StageCalibration)

    def retranslateUi(self, StageCalibration):
        _translate = QtCore.QCoreApplication.translate
        StageCalibration.setWindowTitle(_translate("StageCalibration", "MainWindow"))
        self.executePushButtonWidget.setText(_translate("StageCalibration", "Execute"))
        self.label_3.setText(_translate("StageCalibration", "Lower stage position cutoff"))
        self.label_5.setText(_translate("StageCalibration", "High wavelength cutoff"))
        self.label_2.setText(_translate("StageCalibration", "Low wavelength cutoff"))
        self.saveFileButtonWidget.setText(_translate("StageCalibration", "Save calibration"))
        self.label.setText(_translate("StageCalibration", "Pump wavelength"))
        self.label_4.setText(_translate("StageCalibration", "Higher stage position cutoff"))
        self.undoButtonWidget.setText(_translate("StageCalibration", "Undo"))
        self.loadFileButtonWidget.setText(_translate("StageCalibration", "Load file"))
        self.formulaWidget.setText(_translate("StageCalibration", "Formula"))
        self.saveFileDefaultButtonWidget.setText(_translate("StageCalibration", "Save calibration default"))

