# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThorlabsStage.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Thorlabs(object):
    def setupUi(self, Thorlabs):
        Thorlabs.setObjectName("Thorlabs")
        Thorlabs.resize(403, 346)
        self.gridLayout = QtWidgets.QGridLayout(Thorlabs)
        self.gridLayout.setObjectName("gridLayout")
        self.titleLabel = QtWidgets.QLabel(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 4)
        self.labelPort = QtWidgets.QLabel(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPort.sizePolicy().hasHeightForWidth())
        self.labelPort.setSizePolicy(sizePolicy)
        self.labelPort.setObjectName("labelPort")
        self.gridLayout.addWidget(self.labelPort, 1, 0, 1, 1)
        self.lineEditConnport = QtWidgets.QLineEdit(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConnport.sizePolicy().hasHeightForWidth())
        self.lineEditConnport.setSizePolicy(sizePolicy)
        self.lineEditConnport.setMaxLength(5)
        self.lineEditConnport.setObjectName("lineEditConnport")
        self.gridLayout.addWidget(self.lineEditConnport, 1, 1, 1, 1)
        self.buttonSetPorts = QtWidgets.QPushButton(Thorlabs)
        self.buttonSetPorts.setObjectName("buttonSetPorts")
        self.gridLayout.addWidget(self.buttonSetPorts, 1, 2, 2, 1)
        self.labelSerialNumber = QtWidgets.QLabel(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSerialNumber.sizePolicy().hasHeightForWidth())
        self.labelSerialNumber.setSizePolicy(sizePolicy)
        self.labelSerialNumber.setObjectName("labelSerialNumber")
        self.gridLayout.addWidget(self.labelSerialNumber, 2, 0, 1, 1)
        self.lineEditSerialNumber = QtWidgets.QLineEdit(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSerialNumber.sizePolicy().hasHeightForWidth())
        self.lineEditSerialNumber.setSizePolicy(sizePolicy)
        self.lineEditSerialNumber.setMaxLength(8)
        self.lineEditSerialNumber.setObjectName("lineEditSerialNumber")
        self.gridLayout.addWidget(self.lineEditSerialNumber, 2, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(Thorlabs)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 3, 0, 1, 4)
        self.homeButton = QtWidgets.QPushButton(Thorlabs)
        self.homeButton.setObjectName("homeButton")
        self.gridLayout.addWidget(self.homeButton, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 2, 1, 1)
        self.moveSpeedSpinbox = QtWidgets.QDoubleSpinBox(Thorlabs)
        self.moveSpeedSpinbox.setDecimals(4)
        self.moveSpeedSpinbox.setMinimum(0.0)
        self.moveSpeedSpinbox.setMaximum(10.0)
        self.moveSpeedSpinbox.setSingleStep(0.01)
        self.moveSpeedSpinbox.setObjectName("moveSpeedSpinbox")
        self.gridLayout.addWidget(self.moveSpeedSpinbox, 4, 3, 1, 1)
        self.moveButton1 = QtWidgets.QPushButton(Thorlabs)
        self.moveButton1.setObjectName("moveButton1")
        self.gridLayout.addWidget(self.moveButton1, 5, 0, 1, 1)
        self.moveSpinbox1 = QtWidgets.QDoubleSpinBox(Thorlabs)
        self.moveSpinbox1.setDecimals(4)
        self.moveSpinbox1.setMinimum(0.0)
        self.moveSpinbox1.setMaximum(220.0)
        self.moveSpinbox1.setObjectName("moveSpinbox1")
        self.gridLayout.addWidget(self.moveSpinbox1, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 2, 1, 1)
        self.startPositionSpinbox = QtWidgets.QDoubleSpinBox(Thorlabs)
        self.startPositionSpinbox.setDecimals(4)
        self.startPositionSpinbox.setMinimum(0.0)
        self.startPositionSpinbox.setMaximum(220.0)
        self.startPositionSpinbox.setSingleStep(0.01)
        self.startPositionSpinbox.setObjectName("startPositionSpinbox")
        self.gridLayout.addWidget(self.startPositionSpinbox, 5, 3, 1, 1)
        self.moveButton2 = QtWidgets.QPushButton(Thorlabs)
        self.moveButton2.setObjectName("moveButton2")
        self.gridLayout.addWidget(self.moveButton2, 6, 0, 1, 1)
        self.moveSpinbox2 = QtWidgets.QDoubleSpinBox(Thorlabs)
        self.moveSpinbox2.setDecimals(4)
        self.moveSpinbox2.setMinimum(0.0)
        self.moveSpinbox2.setMaximum(220.0)
        self.moveSpinbox2.setObjectName("moveSpinbox2")
        self.gridLayout.addWidget(self.moveSpinbox2, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 2, 1, 1)
        self.endPositionSpinbox = QtWidgets.QDoubleSpinBox(Thorlabs)
        self.endPositionSpinbox.setDecimals(4)
        self.endPositionSpinbox.setMinimum(0.0)
        self.endPositionSpinbox.setMaximum(220.0)
        self.endPositionSpinbox.setSingleStep(0.01)
        self.endPositionSpinbox.setObjectName("endPositionSpinbox")
        self.gridLayout.addWidget(self.endPositionSpinbox, 6, 3, 1, 1)
        self.moveButton3 = QtWidgets.QPushButton(Thorlabs)
        self.moveButton3.setObjectName("moveButton3")
        self.gridLayout.addWidget(self.moveButton3, 7, 0, 1, 1)
        self.moveSpinbox3 = QtWidgets.QDoubleSpinBox(Thorlabs)
        self.moveSpinbox3.setDecimals(4)
        self.moveSpinbox3.setMinimum(0.0)
        self.moveSpinbox3.setMaximum(400.0)
        self.moveSpinbox3.setObjectName("moveSpinbox3")
        self.gridLayout.addWidget(self.moveSpinbox3, 7, 1, 1, 1)
        self.scanButton = QtWidgets.QPushButton(Thorlabs)
        self.scanButton.setObjectName("scanButton")
        self.gridLayout.addWidget(self.scanButton, 7, 3, 1, 1)
        self.label = QtWidgets.QLabel(Thorlabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.incSpinbox = QtWidgets.QDoubleSpinBox(Thorlabs)
        self.incSpinbox.setDecimals(4)
        self.incSpinbox.setSingleStep(0.1)
        self.incSpinbox.setObjectName("incSpinbox")
        self.gridLayout.addWidget(self.incSpinbox, 8, 1, 1, 1)
        self.upButton = QtWidgets.QPushButton(Thorlabs)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 8, 2, 1, 1)
        self.downButton = QtWidgets.QPushButton(Thorlabs)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 9, 2, 1, 1)
        self.stopButton = QtWidgets.QPushButton(Thorlabs)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 9, 3, 1, 1)

        self.retranslateUi(Thorlabs)
        QtCore.QMetaObject.connectSlotsByName(Thorlabs)

    def retranslateUi(self, Thorlabs):
        _translate = QtCore.QCoreApplication.translate
        Thorlabs.setWindowTitle(_translate("Thorlabs", "Form"))
        self.titleLabel.setText(_translate("Thorlabs", "Thorlabs Stage Controller"))
        self.labelPort.setText(_translate("Thorlabs", "Connection PORT"))
        self.lineEditConnport.setText(_translate("Thorlabs", "10124"))
        self.buttonSetPorts.setText(_translate("Thorlabs", "Set"))
        self.labelSerialNumber.setText(_translate("Thorlabs", "Serial Number"))
        self.lineEditSerialNumber.setText(_translate("Thorlabs", "94839332"))
        self.homeButton.setText(_translate("Thorlabs", "Home"))
        self.label_5.setText(_translate("Thorlabs", "Scan Speed"))
        self.moveButton1.setText(_translate("Thorlabs", "Move"))
        self.label_3.setText(_translate("Thorlabs", "Start Position"))
        self.moveButton2.setText(_translate("Thorlabs", "Move"))
        self.label_4.setText(_translate("Thorlabs", "End Position"))
        self.moveButton3.setText(_translate("Thorlabs", "Move"))
        self.scanButton.setText(_translate("Thorlabs", "Scan"))
        self.label.setText(_translate("Thorlabs", "Move increment"))
        self.upButton.setText(_translate("Thorlabs", "Up"))
        self.downButton.setText(_translate("Thorlabs", "Down"))
        self.stopButton.setText(_translate("Thorlabs", "Stop"))


