# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThorlabsStage.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Thorlabs(object):
    def setupUi(self, Thorlabs):
        Thorlabs.setObjectName("Thorlabs")
        Thorlabs.resize(403, 366)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Thorlabs.sizePolicy().hasHeightForWidth())
        Thorlabs.setSizePolicy(sizePolicy)
        Thorlabs.setMaximumSize(QtCore.QSize(1000, 500))
        self.centralwidget = QtWidgets.QWidget(Thorlabs)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonSetPorts = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSetPorts.setObjectName("buttonSetPorts")
        self.gridLayout.addWidget(self.buttonSetPorts, 1, 2, 2, 1)
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 4)
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 8, 2, 1, 1)
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 9, 2, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 9, 3, 1, 1)
        self.moveButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton1.setObjectName("moveButton1")
        self.gridLayout.addWidget(self.moveButton1, 5, 0, 1, 1)
        self.endPositionSpinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.endPositionSpinbox.setDecimals(4)
        self.endPositionSpinbox.setMinimum(-180.0)
        self.endPositionSpinbox.setMaximum(180.0)
        self.endPositionSpinbox.setSingleStep(0.01)
        self.endPositionSpinbox.setObjectName("endPositionSpinbox")
        self.gridLayout.addWidget(self.endPositionSpinbox, 6, 3, 1, 1)
        self.incSpinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.incSpinbox.setDecimals(4)
        self.incSpinbox.setSingleStep(0.1)
        self.incSpinbox.setObjectName("incSpinbox")
        self.gridLayout.addWidget(self.incSpinbox, 8, 1, 1, 1)
        self.startPositionSpinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.startPositionSpinbox.setDecimals(4)
        self.startPositionSpinbox.setMinimum(-180.0)
        self.startPositionSpinbox.setMaximum(180.0)
        self.startPositionSpinbox.setSingleStep(0.01)
        self.startPositionSpinbox.setObjectName("startPositionSpinbox")
        self.gridLayout.addWidget(self.startPositionSpinbox, 5, 3, 1, 1)
        self.moveButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton2.setObjectName("moveButton2")
        self.gridLayout.addWidget(self.moveButton2, 6, 0, 1, 1)
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setObjectName("homeButton")
        self.gridLayout.addWidget(self.homeButton, 4, 0, 1, 1)
        self.labelPort = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPort.sizePolicy().hasHeightForWidth())
        self.labelPort.setSizePolicy(sizePolicy)
        self.labelPort.setObjectName("labelPort")
        self.gridLayout.addWidget(self.labelPort, 1, 0, 1, 1)
        self.labelSerialNumber = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSerialNumber.sizePolicy().hasHeightForWidth())
        self.labelSerialNumber.setSizePolicy(sizePolicy)
        self.labelSerialNumber.setObjectName("labelSerialNumber")
        self.gridLayout.addWidget(self.labelSerialNumber, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 2, 1, 1)
        self.moveSpinbox3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.moveSpinbox3.setDecimals(4)
        self.moveSpinbox3.setMinimum(-400.0)
        self.moveSpinbox3.setMaximum(400.0)
        self.moveSpinbox3.setObjectName("moveSpinbox3")
        self.gridLayout.addWidget(self.moveSpinbox3, 7, 1, 1, 1)
        self.moveSpinbox1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.moveSpinbox1.setDecimals(4)
        self.moveSpinbox1.setMinimum(-400.0)
        self.moveSpinbox1.setMaximum(400.0)
        self.moveSpinbox1.setObjectName("moveSpinbox1")
        self.gridLayout.addWidget(self.moveSpinbox1, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.scanButton = QtWidgets.QPushButton(self.centralwidget)
        self.scanButton.setObjectName("scanButton")
        self.gridLayout.addWidget(self.scanButton, 7, 3, 1, 1)
        self.moveSpeedSpinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.moveSpeedSpinbox.setDecimals(4)
        self.moveSpeedSpinbox.setMinimum(-180.0)
        self.moveSpeedSpinbox.setMaximum(180.0)
        self.moveSpeedSpinbox.setSingleStep(0.01)
        self.moveSpeedSpinbox.setObjectName("moveSpeedSpinbox")
        self.gridLayout.addWidget(self.moveSpeedSpinbox, 4, 3, 1, 1)
        self.lineEditConnport = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditConnport.sizePolicy().hasHeightForWidth())
        self.lineEditConnport.setSizePolicy(sizePolicy)
        self.lineEditConnport.setMaxLength(5)
        self.lineEditConnport.setObjectName("lineEditConnport")
        self.gridLayout.addWidget(self.lineEditConnport, 1, 1, 1, 1)
        self.moveButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton3.setObjectName("moveButton3")
        self.gridLayout.addWidget(self.moveButton3, 7, 0, 1, 1)
        self.moveSpinbox2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.moveSpinbox2.setDecimals(4)
        self.moveSpinbox2.setMinimum(-400.0)
        self.moveSpinbox2.setMaximum(400.0)
        self.moveSpinbox2.setObjectName("moveSpinbox2")
        self.gridLayout.addWidget(self.moveSpinbox2, 6, 1, 1, 1)
        self.lineEditSerialNumber = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSerialNumber.sizePolicy().hasHeightForWidth())
        self.lineEditSerialNumber.setSizePolicy(sizePolicy)
        self.lineEditSerialNumber.setMaxLength(8)
        self.lineEditSerialNumber.setObjectName("lineEditSerialNumber")
        self.gridLayout.addWidget(self.lineEditSerialNumber, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 2, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 3, 0, 1, 4)
        Thorlabs.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Thorlabs)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRemote = QtWidgets.QMenu(self.menubar)
        self.menuRemote.setObjectName("menuRemote")
        Thorlabs.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Thorlabs)
        self.statusbar.setObjectName("statusbar")
        Thorlabs.setStatusBar(self.statusbar)
        self.action_Connect = QtWidgets.QAction(Thorlabs)
        self.action_Connect.setObjectName("action_Connect")
        self.action_Quit = QtWidgets.QAction(Thorlabs)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Disconnect = QtWidgets.QAction(Thorlabs)
        self.action_Disconnect.setObjectName("action_Disconnect")
        self.menuFile.addAction(self.action_Quit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRemote.menuAction())

        self.retranslateUi(Thorlabs)
        QtCore.QMetaObject.connectSlotsByName(Thorlabs)
        Thorlabs.setTabOrder(self.lineEditConnport, self.lineEditSerialNumber)
        Thorlabs.setTabOrder(self.lineEditSerialNumber, self.buttonSetPorts)
        Thorlabs.setTabOrder(self.buttonSetPorts, self.homeButton)
        Thorlabs.setTabOrder(self.homeButton, self.moveButton1)
        Thorlabs.setTabOrder(self.moveButton1, self.moveSpinbox1)
        Thorlabs.setTabOrder(self.moveSpinbox1, self.moveButton2)
        Thorlabs.setTabOrder(self.moveButton2, self.moveSpinbox2)
        Thorlabs.setTabOrder(self.moveSpinbox2, self.moveButton3)
        Thorlabs.setTabOrder(self.moveButton3, self.moveSpinbox3)
        Thorlabs.setTabOrder(self.moveSpinbox3, self.incSpinbox)
        Thorlabs.setTabOrder(self.incSpinbox, self.moveSpeedSpinbox)
        Thorlabs.setTabOrder(self.moveSpeedSpinbox, self.startPositionSpinbox)
        Thorlabs.setTabOrder(self.startPositionSpinbox, self.endPositionSpinbox)
        Thorlabs.setTabOrder(self.endPositionSpinbox, self.scanButton)
        Thorlabs.setTabOrder(self.scanButton, self.stopButton)

    def retranslateUi(self, Thorlabs):
        _translate = QtCore.QCoreApplication.translate
        Thorlabs.setWindowTitle(_translate("Thorlabs", "MainWindow"))
        self.buttonSetPorts.setText(_translate("Thorlabs", "Set"))
        self.titleLabel.setText(_translate("Thorlabs", "Thorlabs Stage Controller"))
        self.upButton.setText(_translate("Thorlabs", "Up"))
        self.downButton.setText(_translate("Thorlabs", "Down"))
        self.stopButton.setText(_translate("Thorlabs", "Stop"))
        self.moveButton1.setText(_translate("Thorlabs", "Move"))
        self.moveButton2.setText(_translate("Thorlabs", "Move"))
        self.homeButton.setText(_translate("Thorlabs", "Home"))
        self.labelPort.setText(_translate("Thorlabs", "Connection PORT"))
        self.labelSerialNumber.setText(_translate("Thorlabs", "Serial Number"))
        self.label_5.setText(_translate("Thorlabs", "Scan Speed"))
        self.label.setText(_translate("Thorlabs", "Move increment"))
        self.scanButton.setText(_translate("Thorlabs", "Scan"))
        self.lineEditConnport.setText(_translate("Thorlabs", "10124"))
        self.moveButton3.setText(_translate("Thorlabs", "Move"))
        self.lineEditSerialNumber.setText(_translate("Thorlabs", "94839332"))
        self.label_3.setText(_translate("Thorlabs", "Start Position"))
        self.label_4.setText(_translate("Thorlabs", "End Position"))
        self.menuFile.setTitle(_translate("Thorlabs", "File"))
        self.menuRemote.setTitle(_translate("Thorlabs", "&Remote"))
        self.action_Connect.setText(_translate("Thorlabs", "&Connect"))
        self.action_Quit.setText(_translate("Thorlabs", "&Quit"))
        self.action_Disconnect.setText(_translate("Thorlabs", "&Disconnect"))


