# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerUi(object):
    def setupUi(self, ServerUi):
        ServerUi.setObjectName("ServerUi")
        ServerUi.resize(375, 224)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ServerUi.sizePolicy().hasHeightForWidth())
        ServerUi.setSizePolicy(sizePolicy)
        ServerUi.setMaximumSize(QtCore.QSize(375, 300))
        self.centralwidget = QtWidgets.QWidget(ServerUi)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sendButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.sendButtonWidget.setObjectName("sendButtonWidget")
        self.gridLayout.addWidget(self.sendButtonWidget, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.textWidgetSend = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textWidgetSend.sizePolicy().hasHeightForWidth())
        self.textWidgetSend.setSizePolicy(sizePolicy)
        self.textWidgetSend.setMinimumSize(QtCore.QSize(10, 25))
        self.textWidgetSend.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textWidgetSend.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textWidgetSend.setPlainText("")
        self.textWidgetSend.setObjectName("textWidgetSend")
        self.gridLayout.addWidget(self.textWidgetSend, 2, 1, 1, 2)
        self.loadScriptButtonWidget3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadScriptButtonWidget3.sizePolicy().hasHeightForWidth())
        self.loadScriptButtonWidget3.setSizePolicy(sizePolicy)
        self.loadScriptButtonWidget3.setObjectName("loadScriptButtonWidget3")
        self.gridLayout.addWidget(self.loadScriptButtonWidget3, 5, 1, 1, 2)
        self.loadScriptButtonWidget2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadScriptButtonWidget2.sizePolicy().hasHeightForWidth())
        self.loadScriptButtonWidget2.setSizePolicy(sizePolicy)
        self.loadScriptButtonWidget2.setObjectName("loadScriptButtonWidget2")
        self.gridLayout.addWidget(self.loadScriptButtonWidget2, 4, 1, 1, 2)
        self.runScriptButtonWidget1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runScriptButtonWidget1.sizePolicy().hasHeightForWidth())
        self.runScriptButtonWidget1.setSizePolicy(sizePolicy)
        self.runScriptButtonWidget1.setObjectName("runScriptButtonWidget1")
        self.gridLayout.addWidget(self.runScriptButtonWidget1, 3, 3, 1, 1)
        self.portComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.portComboBox.setObjectName("portComboBox")
        self.gridLayout.addWidget(self.portComboBox, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 3, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.loadScriptButtonWidget1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadScriptButtonWidget1.sizePolicy().hasHeightForWidth())
        self.loadScriptButtonWidget1.setSizePolicy(sizePolicy)
        self.loadScriptButtonWidget1.setObjectName("loadScriptButtonWidget1")
        self.gridLayout.addWidget(self.loadScriptButtonWidget1, 3, 1, 1, 2)
        self.portNumber = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portNumber.sizePolicy().hasHeightForWidth())
        self.portNumber.setSizePolicy(sizePolicy)
        self.portNumber.setMinimumSize(QtCore.QSize(10, 25))
        self.portNumber.setMaximumSize(QtCore.QSize(16777215, 25))
        self.portNumber.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.portNumber.setObjectName("portNumber")
        self.gridLayout.addWidget(self.portNumber, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(94, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.runScriptButtonWidget3 = QtWidgets.QPushButton(self.centralwidget)
        self.runScriptButtonWidget3.setObjectName("runScriptButtonWidget3")
        self.gridLayout.addWidget(self.runScriptButtonWidget3, 5, 3, 1, 1)
        self.runScriptButtonWidget2 = QtWidgets.QPushButton(self.centralwidget)
        self.runScriptButtonWidget2.setObjectName("runScriptButtonWidget2")
        self.gridLayout.addWidget(self.runScriptButtonWidget2, 4, 3, 1, 1)
        ServerUi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ServerUi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ServerUi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ServerUi)
        self.statusbar.setObjectName("statusbar")
        ServerUi.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(ServerUi)
        self.action_Quit.setObjectName("action_Quit")
        self.actionStart = QtWidgets.QAction(ServerUi)
        self.actionStart.setEnabled(False)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(ServerUi)
        self.actionStop.setEnabled(False)
        self.actionStop.setObjectName("actionStop")
        self.menuFile.addAction(self.action_Quit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ServerUi)
        QtCore.QMetaObject.connectSlotsByName(ServerUi)

    def retranslateUi(self, ServerUi):
        _translate = QtCore.QCoreApplication.translate
        ServerUi.setWindowTitle(_translate("ServerUi", "MainWindow"))
        self.sendButtonWidget.setText(_translate("ServerUi", "Send"))
        self.label_6.setText(_translate("ServerUi", "Message"))
        self.loadScriptButtonWidget3.setText(_translate("ServerUi", "Load Script"))
        self.loadScriptButtonWidget2.setText(_translate("ServerUi", "Load Script"))
        self.runScriptButtonWidget1.setText(_translate("ServerUi", "Run script"))
        self.label_4.setText(_translate("ServerUi", "Port"))
        self.loadScriptButtonWidget1.setText(_translate("ServerUi", "Load Script"))
        self.portNumber.setPlainText(_translate("ServerUi", "10120"))
        self.runScriptButtonWidget3.setText(_translate("ServerUi", "Run script"))
        self.runScriptButtonWidget2.setText(_translate("ServerUi", "Run script"))
        self.menuFile.setTitle(_translate("ServerUi", "File"))
        self.action_Quit.setText(_translate("ServerUi", "&Quit"))
        self.actionStart.setText(_translate("ServerUi", "&Start"))
        self.actionStop.setText(_translate("ServerUi", "&Stop"))


