# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'focusController.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_focusController(object):
    def setupUi(self, focusController):
        focusController.setObjectName("focusController")
        focusController.resize(248, 279)
        focusController.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(focusController)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelComport = QtWidgets.QLabel(self.centralwidget)
        self.labelComport.setObjectName("labelComport")
        self.gridLayout.addWidget(self.labelComport, 0, 0, 1, 1)
        self.labelComport_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelComport_2.setObjectName("labelComport_2")
        self.gridLayout.addWidget(self.labelComport_2, 1, 0, 1, 1)
        self.lineEditComport = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditComport.setObjectName("lineEditComport")
        self.gridLayout.addWidget(self.lineEditComport, 0, 1, 1, 1)
        self.buttonSetPorts = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSetPorts.setObjectName("buttonSetPorts")
        self.gridLayout.addWidget(self.buttonSetPorts, 0, 2, 2, 1)
        self.moveButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton1.setObjectName("moveButton1")
        self.gridLayout.addWidget(self.moveButton1, 4, 0, 1, 1)
        self.moveSpinbox1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.moveSpinbox1.setDecimals(1)
        self.moveSpinbox1.setMinimum(0.0)
        self.moveSpinbox1.setMaximum(6000.0)
        self.moveSpinbox1.setSingleStep(100.0)
        self.moveSpinbox1.setObjectName("moveSpinbox1")
        self.gridLayout.addWidget(self.moveSpinbox1, 4, 1, 1, 1)
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setObjectName("homeButton")
        self.gridLayout.addWidget(self.homeButton, 3, 0, 1, 1)
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget)
        self.zeroButton.setMaximumSize(QtCore.QSize(16777215, 16777209))
        self.zeroButton.setObjectName("zeroButton")
        self.gridLayout.addWidget(self.zeroButton, 3, 2, 1, 1)
        self.incSpinbox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.incSpinbox.setDecimals(1)
        self.incSpinbox.setMinimum(0.1)
        self.incSpinbox.setMaximum(1000.0)
        self.incSpinbox.setSingleStep(0.1)
        self.incSpinbox.setObjectName("incSpinbox")
        self.gridLayout.addWidget(self.incSpinbox, 5, 2, 1, 1)
        self.moveButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton2.setObjectName("moveButton2")
        self.gridLayout.addWidget(self.moveButton2, 5, 0, 1, 1)
        self.moveButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton3.setObjectName("moveButton3")
        self.gridLayout.addWidget(self.moveButton3, 6, 0, 1, 1)
        self.moveSpinbox3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.moveSpinbox3.setDecimals(1)
        self.moveSpinbox3.setMinimum(0.0)
        self.moveSpinbox3.setMaximum(6000.0)
        self.moveSpinbox3.setSingleStep(100.0)
        self.moveSpinbox3.setObjectName("moveSpinbox3")
        self.gridLayout.addWidget(self.moveSpinbox3, 6, 1, 1, 1)
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 7, 2, 1, 1)
        self.lineEditConnport = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditConnport.setObjectName("lineEditConnport")
        self.gridLayout.addWidget(self.lineEditConnport, 1, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 2, 0, 1, 3)
        self.moveSpinbox2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.moveSpinbox2.setDecimals(1)
        self.moveSpinbox2.setMinimum(0.0)
        self.moveSpinbox2.setMaximum(6000.0)
        self.moveSpinbox2.setSingleStep(100.0)
        self.moveSpinbox2.setObjectName("moveSpinbox2")
        self.gridLayout.addWidget(self.moveSpinbox2, 5, 1, 1, 1)
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 6, 2, 1, 1)
        focusController.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(focusController)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 248, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRemote = QtWidgets.QMenu(self.menubar)
        self.menuRemote.setObjectName("menuRemote")
        focusController.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(focusController)
        self.statusbar.setObjectName("statusbar")
        focusController.setStatusBar(self.statusbar)
        self.action_Connect = QtWidgets.QAction(focusController)
        self.action_Connect.setObjectName("action_Connect")
        self.action_Quit = QtWidgets.QAction(focusController)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Disconnect = QtWidgets.QAction(focusController)
        self.action_Disconnect.setObjectName("action_Disconnect")
        self.menuFile.addAction(self.action_Quit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRemote.menuAction())

        self.retranslateUi(focusController)
        QtCore.QMetaObject.connectSlotsByName(focusController)

    def retranslateUi(self, focusController):
        _translate = QtCore.QCoreApplication.translate
        focusController.setWindowTitle(_translate("focusController", "MainWindow"))
        self.labelComport.setText(_translate("focusController", "COM PORT"))
        self.labelComport_2.setText(_translate("focusController", "Connection PORT"))
        self.lineEditComport.setText(_translate("focusController", "COM5"))
        self.buttonSetPorts.setText(_translate("focusController", "Set"))
        self.moveButton1.setText(_translate("focusController", "Move"))
        self.homeButton.setText(_translate("focusController", "Home"))
        self.zeroButton.setText(_translate("focusController", "Zero"))
        self.moveButton2.setText(_translate("focusController", "Move"))
        self.moveButton3.setText(_translate("focusController", "Move"))
        self.downButton.setText(_translate("focusController", "Down"))
        self.lineEditConnport.setText(_translate("focusController", "10125"))
        self.upButton.setText(_translate("focusController", "Up"))
        self.menuFile.setTitle(_translate("focusController", "File"))
        self.menuRemote.setTitle(_translate("focusController", "&Remote"))
        self.action_Connect.setText(_translate("focusController", "&Connect"))
        self.action_Quit.setText(_translate("focusController", "&Quit"))
        self.action_Disconnect.setText(_translate("focusController", "&Disconnect"))


