# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Microscoper.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Microscoper(object):
    def setupUi(self, Microscoper):
        Microscoper.setObjectName("Microscoper")
        Microscoper.setEnabled(True)
        Microscoper.resize(983, 305)
        Microscoper.setMaximumSize(QtCore.QSize(1461, 500))
        self.centralwidget = QtWidgets.QWidget(Microscoper)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.microcopeOffsetRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.microcopeOffsetRadio.setObjectName("microcopeOffsetRadio")
        self.gridLayout.addWidget(self.microcopeOffsetRadio, 0, 4, 1, 1)
        self.deltaOffsetLabel = QtWidgets.QLabel(self.centralwidget)
        self.deltaOffsetLabel.setObjectName("deltaOffsetLabel")
        self.gridLayout.addWidget(self.deltaOffsetLabel, 0, 5, 1, 1)
        self.PMTStatusText = QtWidgets.QLabel(self.centralwidget)
        self.PMTStatusText.setObjectName("PMTStatusText")
        self.gridLayout.addWidget(self.PMTStatusText, 0, 7, 1, 1)
        self.PMTLabel0 = QtWidgets.QLabel(self.centralwidget)
        self.PMTLabel0.setObjectName("PMTLabel0")
        self.gridLayout.addWidget(self.PMTLabel0, 0, 8, 1, 1)
        self.PMTLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.PMTLabel1.setObjectName("PMTLabel1")
        self.gridLayout.addWidget(self.PMTLabel1, 0, 9, 1, 1)
        self.PMTLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.PMTLabel2.setObjectName("PMTLabel2")
        self.gridLayout.addWidget(self.PMTLabel2, 0, 10, 1, 1)
        self.PMTLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.PMTLabel3.setObjectName("PMTLabel3")
        self.gridLayout.addWidget(self.PMTLabel3, 0, 11, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.filenameText = QtWidgets.QLineEdit(self.centralwidget)
        self.filenameText.setObjectName("filenameText")
        self.gridLayout.addWidget(self.filenameText, 1, 1, 1, 2)
        self.saveCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.saveCheckBox.setObjectName("saveCheckBox")
        self.gridLayout.addWidget(self.saveCheckBox, 1, 3, 1, 1)
        self.galvoOffsetRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.galvoOffsetRadio.setChecked(True)
        self.galvoOffsetRadio.setObjectName("galvoOffsetRadio")
        self.gridLayout.addWidget(self.galvoOffsetRadio, 1, 4, 1, 1)
        self.deltaOffset = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deltaOffset.sizePolicy().hasHeightForWidth())
        self.deltaOffset.setSizePolicy(sizePolicy)
        self.deltaOffset.setMaximumSize(QtCore.QSize(70, 100))
        self.deltaOffset.setDecimals(4)
        self.deltaOffset.setMaximum(220.0)
        self.deltaOffset.setSingleStep(0.1)
        self.deltaOffset.setProperty("value", 1.0)
        self.deltaOffset.setObjectName("deltaOffset")
        self.gridLayout.addWidget(self.deltaOffset, 1, 5, 1, 1)
        self.PMTSlider0 = QtWidgets.QSlider(self.centralwidget)
        self.PMTSlider0.setMaximum(1000)
        self.PMTSlider0.setOrientation(QtCore.Qt.Vertical)
        self.PMTSlider0.setTickInterval(0)
        self.PMTSlider0.setObjectName("PMTSlider0")
        self.gridLayout.addWidget(self.PMTSlider0, 1, 8, 3, 1)
        self.PMTSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.PMTSlider1.setMaximum(1000)
        self.PMTSlider1.setOrientation(QtCore.Qt.Vertical)
        self.PMTSlider1.setObjectName("PMTSlider1")
        self.gridLayout.addWidget(self.PMTSlider1, 1, 9, 3, 1)
        self.PMTSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.PMTSlider2.setMaximum(1000)
        self.PMTSlider2.setOrientation(QtCore.Qt.Vertical)
        self.PMTSlider2.setObjectName("PMTSlider2")
        self.gridLayout.addWidget(self.PMTSlider2, 1, 10, 3, 1)
        self.PMTSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.PMTSlider3.setMaximum(1000)
        self.PMTSlider3.setOrientation(QtCore.Qt.Vertical)
        self.PMTSlider3.setObjectName("PMTSlider3")
        self.gridLayout.addWidget(self.PMTSlider3, 1, 11, 3, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.directoryText = QtWidgets.QLineEdit(self.centralwidget)
        self.directoryText.setText("")
        self.directoryText.setObjectName("directoryText")
        self.gridLayout.addWidget(self.directoryText, 2, 1, 1, 2)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 2, 3, 1, 1)
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 3, 5, 1, 1)
        self.ZoomLabel = QtWidgets.QLabel(self.centralwidget)
        self.ZoomLabel.setObjectName("ZoomLabel")
        self.gridLayout.addWidget(self.ZoomLabel, 4, 0, 1, 1)
        self.zoomWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zoomWidget.setDecimals(0)
        self.zoomWidget.setMinimum(1.0)
        self.zoomWidget.setMaximum(500.0)
        self.zoomWidget.setProperty("value", 1.0)
        self.zoomWidget.setObjectName("zoomWidget")
        self.gridLayout.addWidget(self.zoomWidget, 4, 1, 1, 1)
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton.sizePolicy().hasHeightForWidth())
        self.leftButton.setSizePolicy(sizePolicy)
        self.leftButton.setObjectName("leftButton")
        self.gridLayout.addWidget(self.leftButton, 4, 4, 1, 1)
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightButton.sizePolicy().hasHeightForWidth())
        self.rightButton.setSizePolicy(sizePolicy)
        self.rightButton.setObjectName("rightButton")
        self.gridLayout.addWidget(self.rightButton, 4, 6, 1, 1)
        self.pumpShutterButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pumpShutterButton.sizePolicy().hasHeightForWidth())
        self.pumpShutterButton.setSizePolicy(sizePolicy)
        self.pumpShutterButton.setObjectName("pumpShutterButton")
        self.gridLayout.addWidget(self.pumpShutterButton, 4, 7, 1, 1)
        self.PMTPreset0 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTPreset0.setObjectName("PMTPreset0")
        self.gridLayout.addWidget(self.PMTPreset0, 4, 8, 1, 1)
        self.PMTPreset1 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTPreset1.setObjectName("PMTPreset1")
        self.gridLayout.addWidget(self.PMTPreset1, 4, 9, 1, 1)
        self.PMTPreset2 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTPreset2.setObjectName("PMTPreset2")
        self.gridLayout.addWidget(self.PMTPreset2, 4, 10, 1, 1)
        self.PMTPreset3 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTPreset3.setObjectName("PMTPreset3")
        self.gridLayout.addWidget(self.PMTPreset3, 4, 11, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.dwellTime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dwellTime.setDecimals(0)
        self.dwellTime.setMinimum(1.0)
        self.dwellTime.setProperty("value", 2.0)
        self.dwellTime.setObjectName("dwellTime")
        self.gridLayout.addWidget(self.dwellTime, 5, 1, 1, 1)
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 5, 5, 1, 1)
        self.stokesShutterButton = QtWidgets.QPushButton(self.centralwidget)
        self.stokesShutterButton.setObjectName("stokesShutterButton")
        self.gridLayout.addWidget(self.stokesShutterButton, 5, 7, 1, 1)
        self.PMTZero0 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTZero0.setObjectName("PMTZero0")
        self.gridLayout.addWidget(self.PMTZero0, 5, 8, 1, 1)
        self.PMTZero1 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTZero1.setObjectName("PMTZero1")
        self.gridLayout.addWidget(self.PMTZero1, 5, 9, 1, 1)
        self.PMTZero2 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTZero2.setObjectName("PMTZero2")
        self.gridLayout.addWidget(self.PMTZero2, 5, 10, 1, 1)
        self.PMTZero3 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTZero3.setObjectName("PMTZero3")
        self.gridLayout.addWidget(self.PMTZero3, 5, 11, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.resolutionWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.resolutionWidget.setDecimals(0)
        self.resolutionWidget.setMinimum(10.0)
        self.resolutionWidget.setMaximum(2000.0)
        self.resolutionWidget.setSingleStep(50.0)
        self.resolutionWidget.setProperty("value", 50.0)
        self.resolutionWidget.setObjectName("resolutionWidget")
        self.gridLayout.addWidget(self.resolutionWidget, 6, 1, 1, 1)
        self.pmtInvert1 = QtWidgets.QCheckBox(self.centralwidget)
        self.pmtInvert1.setObjectName("pmtInvert1")
        self.gridLayout.addWidget(self.pmtInvert1, 6, 8, 1, 1)
        self.pmtInvert2 = QtWidgets.QCheckBox(self.centralwidget)
        self.pmtInvert2.setObjectName("pmtInvert2")
        self.gridLayout.addWidget(self.pmtInvert2, 6, 9, 1, 1)
        self.pmtInvert3 = QtWidgets.QCheckBox(self.centralwidget)
        self.pmtInvert3.setObjectName("pmtInvert3")
        self.gridLayout.addWidget(self.pmtInvert3, 6, 10, 1, 1)
        self.pmtInvert4 = QtWidgets.QCheckBox(self.centralwidget)
        self.pmtInvert4.setObjectName("pmtInvert4")
        self.gridLayout.addWidget(self.pmtInvert4, 6, 11, 1, 1)
        self.scansToAverageLabel = QtWidgets.QLabel(self.centralwidget)
        self.scansToAverageLabel.setObjectName("scansToAverageLabel")
        self.gridLayout.addWidget(self.scansToAverageLabel, 7, 0, 1, 1)
        self.scansToAverage = QtWidgets.QSpinBox(self.centralwidget)
        self.scansToAverage.setMinimum(1)
        self.scansToAverage.setObjectName("scansToAverage")
        self.gridLayout.addWidget(self.scansToAverage, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 4, 1, 1)
        self.fillFractionLabel = QtWidgets.QLabel(self.centralwidget)
        self.fillFractionLabel.setObjectName("fillFractionLabel")
        self.gridLayout.addWidget(self.fillFractionLabel, 8, 0, 1, 1)
        self.fillFractionWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.fillFractionWidget.setDecimals(1)
        self.fillFractionWidget.setMinimum(0.0)
        self.fillFractionWidget.setMaximum(2000.0)
        self.fillFractionWidget.setSingleStep(0.2)
        self.fillFractionWidget.setProperty("value", 1.0)
        self.fillFractionWidget.setObjectName("fillFractionWidget")
        self.gridLayout.addWidget(self.fillFractionWidget, 8, 1, 1, 1)
        self.calibrationFilenameText = QtWidgets.QLineEdit(self.centralwidget)
        self.calibrationFilenameText.setObjectName("calibrationFilenameText")
        self.gridLayout.addWidget(self.calibrationFilenameText, 8, 4, 1, 2)
        self.scanTypeWidget = QtWidgets.QComboBox(self.centralwidget)
        self.scanTypeWidget.setObjectName("scanTypeWidget")
        self.gridLayout.addWidget(self.scanTypeWidget, 0, 3, 1, 1)
        self.acquireButton = QtWidgets.QPushButton(self.centralwidget)
        self.acquireButton.setObjectName("acquireButton")
        self.gridLayout.addWidget(self.acquireButton, 0, 0, 1, 3)
        self.browseCalibrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseCalibrationButton.setObjectName("browseCalibrationButton")
        self.gridLayout.addWidget(self.browseCalibrationButton, 8, 6, 1, 1)
        self.WavenumberText = QtWidgets.QLabel(self.centralwidget)
        self.WavenumberText.setObjectName("WavenumberText")
        self.gridLayout.addWidget(self.WavenumberText, 7, 5, 1, 2)
        self.zeroOffsetButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zeroOffsetButton.sizePolicy().hasHeightForWidth())
        self.zeroOffsetButton.setSizePolicy(sizePolicy)
        self.zeroOffsetButton.setObjectName("zeroOffsetButton")
        self.gridLayout.addWidget(self.zeroOffsetButton, 4, 5, 1, 1)
        Microscoper.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Microscoper)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 983, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        Microscoper.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Microscoper)
        self.statusbar.setObjectName("statusbar")
        Microscoper.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(Microscoper)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Open = QtWidgets.QAction(Microscoper)
        self.action_Open.setObjectName("action_Open")
        self.action_About = QtWidgets.QAction(Microscoper)
        self.action_About.setObjectName("action_About")
        self.action_setImageLevels = QtWidgets.QAction(Microscoper)
        self.action_setImageLevels.setObjectName("action_setImageLevels")
        self.action_Spectrometer = QtWidgets.QAction(Microscoper)
        self.action_Spectrometer.setObjectName("action_Spectrometer")
        self.action_Rotation_Stage = QtWidgets.QAction(Microscoper)
        self.action_Rotation_Stage.setObjectName("action_Rotation_Stage")
        self.actionBring_all_to_front = QtWidgets.QAction(Microscoper)
        self.actionBring_all_to_front.setObjectName("actionBring_all_to_front")
        self.action_Connect = QtWidgets.QAction(Microscoper)
        self.action_Connect.setObjectName("action_Connect")
        self.action_Disconnect = QtWidgets.QAction(Microscoper)
        self.action_Disconnect.setObjectName("action_Disconnect")
        self.menuFile.addAction(self.action_Quit)
        self.menuSettings.addAction(self.action_setImageLevels)
        self.menuWindow.addAction(self.actionBring_all_to_front)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(Microscoper)
        QtCore.QMetaObject.connectSlotsByName(Microscoper)

    def retranslateUi(self, Microscoper):
        _translate = QtCore.QCoreApplication.translate
        Microscoper.setWindowTitle(_translate("Microscoper", "MainWindow"))
        self.microcopeOffsetRadio.setText(_translate("Microscoper", "XYStage"))
        self.deltaOffsetLabel.setText(_translate("Microscoper", "dOffset (V)"))
        self.PMTStatusText.setText(_translate("Microscoper", "PMT Status : Off"))
        self.PMTLabel0.setText(_translate("Microscoper", "0"))
        self.PMTLabel1.setText(_translate("Microscoper", "0"))
        self.PMTLabel2.setText(_translate("Microscoper", "0"))
        self.PMTLabel3.setText(_translate("Microscoper", "0"))
        self.label.setText(_translate("Microscoper", "Filename"))
        self.saveCheckBox.setText(_translate("Microscoper", "Save"))
        self.galvoOffsetRadio.setText(_translate("Microscoper", "Galvo"))
        self.label_2.setText(_translate("Microscoper", "Directory"))
        self.browseButton.setText(_translate("Microscoper", "Browse"))
        self.upButton.setText(_translate("Microscoper", "Up"))
        self.ZoomLabel.setText(_translate("Microscoper", "Zoom"))
        self.leftButton.setText(_translate("Microscoper", "Left"))
        self.rightButton.setText(_translate("Microscoper", "Right"))
        self.pumpShutterButton.setText(_translate("Microscoper", "Pump"))
        self.PMTPreset0.setText(_translate("Microscoper", "700"))
        self.PMTPreset1.setText(_translate("Microscoper", "700"))
        self.PMTPreset2.setText(_translate("Microscoper", "700"))
        self.PMTPreset3.setText(_translate("Microscoper", "700"))
        self.label_4.setText(_translate("Microscoper", "line dwell time (ms)"))
        self.downButton.setText(_translate("Microscoper", "Down"))
        self.stokesShutterButton.setText(_translate("Microscoper", "Stokes"))
        self.PMTZero0.setText(_translate("Microscoper", "Zero"))
        self.PMTZero1.setText(_translate("Microscoper", "Zero"))
        self.PMTZero2.setText(_translate("Microscoper", "Zero"))
        self.PMTZero3.setText(_translate("Microscoper", "Zero"))
        self.label_3.setText(_translate("Microscoper", "Resolution (px)"))
        self.pmtInvert1.setText(_translate("Microscoper", "Invert"))
        self.pmtInvert2.setText(_translate("Microscoper", "Invert"))
        self.pmtInvert3.setText(_translate("Microscoper", "Invert"))
        self.pmtInvert4.setText(_translate("Microscoper", "Invert"))
        self.scansToAverageLabel.setText(_translate("Microscoper", "Frames to average"))
        self.label_5.setText(_translate("Microscoper", "Calibration"))
        self.fillFractionLabel.setText(_translate("Microscoper", "Fill fraction"))
        self.acquireButton.setText(_translate("Microscoper", "Acquire"))
        self.browseCalibrationButton.setText(_translate("Microscoper", "Browse"))
        self.WavenumberText.setText(_translate("Microscoper", "0 cm-1"))
        self.zeroOffsetButton.setText(_translate("Microscoper", "Zero"))
        self.menuFile.setTitle(_translate("Microscoper", "File"))
        self.menuSettings.setTitle(_translate("Microscoper", "Settings"))
        self.menuWindow.setTitle(_translate("Microscoper", "Window"))
        self.action_Quit.setText(_translate("Microscoper", "&Quit"))
        self.action_Open.setText(_translate("Microscoper", "&Open TIFF"))
        self.action_About.setText(_translate("Microscoper", "&About"))
        self.action_setImageLevels.setText(_translate("Microscoper", "&Image Levels"))
        self.action_Spectrometer.setText(_translate("Microscoper", "&Spectrometer"))
        self.action_Rotation_Stage.setText(_translate("Microscoper", "&Rotation Stage"))
        self.actionBring_all_to_front.setText(_translate("Microscoper", "Bring all to front"))
        self.action_Connect.setText(_translate("Microscoper", "&Connect"))
        self.action_Disconnect.setText(_translate("Microscoper", "&Disconnect"))


