# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Microscoper_gui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Microscoper2017(object):
    def setupUi(self, Microscoper2017):
        Microscoper2017.setObjectName("Microscoper2017")
        Microscoper2017.setEnabled(True)
        Microscoper2017.resize(1230, 300)
        Microscoper2017.setMaximumSize(QtCore.QSize(1230, 300))
        self.centralwidget = QtWidgets.QWidget(Microscoper2017)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.deltaOffsetLabel = QtWidgets.QLabel(self.centralwidget)
        self.deltaOffsetLabel.setObjectName("deltaOffsetLabel")
        self.gridLayout_8.addWidget(self.deltaOffsetLabel, 0, 1, 1, 1)
        self.microcopeOffsetRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.microcopeOffsetRadio.setObjectName("microcopeOffsetRadio")
        self.gridLayout_8.addWidget(self.microcopeOffsetRadio, 0, 0, 1, 1)
        self.galvoOffsetRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.galvoOffsetRadio.setChecked(True)
        self.galvoOffsetRadio.setObjectName("galvoOffsetRadio")
        self.gridLayout_8.addWidget(self.galvoOffsetRadio, 1, 0, 1, 1)
        self.deltaOffset = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.deltaOffset.setDecimals(4)
        self.deltaOffset.setMaximum(220.0)
        self.deltaOffset.setSingleStep(0.1)
        self.deltaOffset.setProperty("value", 1.0)
        self.deltaOffset.setObjectName("deltaOffset")
        self.gridLayout_8.addWidget(self.deltaOffset, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_8, 2, 4, 2, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setObjectName("upButton")
        self.gridLayout_2.addWidget(self.upButton, 0, 1, 1, 1)
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftButton.sizePolicy().hasHeightForWidth())
        self.leftButton.setSizePolicy(sizePolicy)
        self.leftButton.setObjectName("leftButton")
        self.gridLayout_2.addWidget(self.leftButton, 1, 0, 1, 1)
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downButton.sizePolicy().hasHeightForWidth())
        self.downButton.setSizePolicy(sizePolicy)
        self.downButton.setObjectName("downButton")
        self.gridLayout_2.addWidget(self.downButton, 2, 1, 1, 1)
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightButton.sizePolicy().hasHeightForWidth())
        self.rightButton.setSizePolicy(sizePolicy)
        self.rightButton.setObjectName("rightButton")
        self.gridLayout_2.addWidget(self.rightButton, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 5, 4, 4, 1)
        self.DirectoryText = QtWidgets.QLineEdit(self.centralwidget)
        self.DirectoryText.setText("")
        self.DirectoryText.setObjectName("DirectoryText")
        self.gridLayout_3.addWidget(self.DirectoryText, 3, 1, 1, 2)
        self.FilenameText = QtWidgets.QLineEdit(self.centralwidget)
        self.FilenameText.setObjectName("FilenameText")
        self.gridLayout_3.addWidget(self.FilenameText, 2, 1, 1, 3)
        self.scanTypeWidget = QtWidgets.QComboBox(self.centralwidget)
        self.scanTypeWidget.setObjectName("scanTypeWidget")
        self.gridLayout_3.addWidget(self.scanTypeWidget, 0, 6, 2, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout_3.addWidget(self.browseButton, 3, 3, 2, 1)
        self.AcquireButton = QtWidgets.QPushButton(self.centralwidget)
        self.AcquireButton.setObjectName("AcquireButton")
        self.gridLayout_3.addWidget(self.AcquireButton, 0, 0, 2, 6)
        self.saveCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.saveCheckBox.setObjectName("saveCheckBox")
        self.gridLayout_3.addWidget(self.saveCheckBox, 5, 3, 1, 1)
        self.ZStageMove = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ZStageMove.setDecimals(5)
        self.ZStageMove.setMinimum(0.0001)
        self.ZStageMove.setMaximum(500.0)
        self.ZStageMove.setSingleStep(10.0)
        self.ZStageMove.setProperty("value", 0.05)
        self.ZStageMove.setObjectName("ZStageMove")
        self.gridLayout_3.addWidget(self.ZStageMove, 9, 10, 1, 1)
        self.LStageEndLabel = QtWidgets.QLabel(self.centralwidget)
        self.LStageEndLabel.setObjectName("LStageEndLabel")
        self.gridLayout_3.addWidget(self.LStageEndLabel, 8, 8, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 9, 4, 2, 1)
        self.LStageStartLabel = QtWidgets.QLabel(self.centralwidget)
        self.LStageStartLabel.setObjectName("LStageStartLabel")
        self.gridLayout_3.addWidget(self.LStageStartLabel, 7, 8, 1, 1)
        self.CalibrationFilenameText = QtWidgets.QLineEdit(self.centralwidget)
        self.CalibrationFilenameText.setObjectName("CalibrationFilenameText")
        self.gridLayout_3.addWidget(self.CalibrationFilenameText, 11, 4, 2, 3)
        self.LStageMove = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LStageMove.setDecimals(5)
        self.LStageMove.setMinimum(0.0001)
        self.LStageMove.setMaximum(500.0)
        self.LStageMove.setSingleStep(10.0)
        self.LStageMove.setProperty("value", 0.05)
        self.LStageMove.setObjectName("LStageMove")
        self.gridLayout_3.addWidget(self.LStageMove, 9, 9, 1, 1)
        self.browseCalibrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseCalibrationButton.setObjectName("browseCalibrationButton")
        self.gridLayout_3.addWidget(self.browseCalibrationButton, 11, 7, 2, 1)
        self.LStageEnd = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LStageEnd.setMaximum(999.0)
        self.LStageEnd.setProperty("value", 105.0)
        self.LStageEnd.setObjectName("LStageEnd")
        self.gridLayout_3.addWidget(self.LStageEnd, 8, 9, 1, 1)
        self.WavenumberText = QtWidgets.QLabel(self.centralwidget)
        self.WavenumberText.setObjectName("WavenumberText")
        self.gridLayout_3.addWidget(self.WavenumberText, 13, 5, 1, 2)
        self.ZStageEnd = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ZStageEnd.setMaximum(999.0)
        self.ZStageEnd.setProperty("value", 105.0)
        self.ZStageEnd.setObjectName("ZStageEnd")
        self.gridLayout_3.addWidget(self.ZStageEnd, 8, 10, 1, 1)
        self.ZStageStart = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ZStageStart.setMaximum(999.0)
        self.ZStageStart.setProperty("value", 100.0)
        self.ZStageStart.setObjectName("ZStageStart")
        self.gridLayout_3.addWidget(self.ZStageStart, 7, 10, 1, 1)
        self.LStageMoveLabel = QtWidgets.QLabel(self.centralwidget)
        self.LStageMoveLabel.setObjectName("LStageMoveLabel")
        self.gridLayout_3.addWidget(self.LStageMoveLabel, 9, 8, 1, 1)
        self.LStageStart = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LStageStart.setMaximum(999.0)
        self.LStageStart.setProperty("value", 100.0)
        self.LStageStart.setObjectName("LStageStart")
        self.gridLayout_3.addWidget(self.LStageStart, 7, 9, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 10, 2, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.currentYStagePositionLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentYStagePositionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentYStagePositionLabel.setObjectName("currentYStagePositionLabel")
        self.gridLayout_7.addWidget(self.currentYStagePositionLabel, 0, 2, 1, 1)
        self.yStagePresetWidget1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.yStagePresetWidget1.setDecimals(3)
        self.yStagePresetWidget1.setObjectName("yStagePresetWidget1")
        self.gridLayout_7.addWidget(self.yStagePresetWidget1, 3, 2, 1, 1)
        self.currentYStagePositionText = QtWidgets.QLabel(self.centralwidget)
        self.currentYStagePositionText.setObjectName("currentYStagePositionText")
        self.gridLayout_7.addWidget(self.currentYStagePositionText, 1, 2, 1, 1)
        self.currentXStagePositionLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentXStagePositionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentXStagePositionLabel.setObjectName("currentXStagePositionLabel")
        self.gridLayout_7.addWidget(self.currentXStagePositionLabel, 0, 1, 1, 1)
        self.zStagePresetWidget1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zStagePresetWidget1.setDecimals(1)
        self.zStagePresetWidget1.setMinimum(-1000.0)
        self.zStagePresetWidget1.setMaximum(1000.0)
        self.zStagePresetWidget1.setObjectName("zStagePresetWidget1")
        self.gridLayout_7.addWidget(self.zStagePresetWidget1, 3, 3, 1, 1)
        self.currentXStagePositionText = QtWidgets.QLabel(self.centralwidget)
        self.currentXStagePositionText.setObjectName("currentXStagePositionText")
        self.gridLayout_7.addWidget(self.currentXStagePositionText, 1, 1, 1, 1)
        self.currentZStagePositionLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentZStagePositionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentZStagePositionLabel.setObjectName("currentZStagePositionLabel")
        self.gridLayout_7.addWidget(self.currentZStagePositionLabel, 0, 3, 1, 1)
        self.currentZStagePositionText = QtWidgets.QLabel(self.centralwidget)
        self.currentZStagePositionText.setObjectName("currentZStagePositionText")
        self.gridLayout_7.addWidget(self.currentZStagePositionText, 1, 3, 1, 1)
        self.yPresetButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.yPresetButton1.setObjectName("yPresetButton1")
        self.gridLayout_7.addWidget(self.yPresetButton1, 4, 2, 1, 1)
        self.xStagePresetWidget1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xStagePresetWidget1.setDecimals(3)
        self.xStagePresetWidget1.setObjectName("xStagePresetWidget1")
        self.gridLayout_7.addWidget(self.xStagePresetWidget1, 3, 1, 1, 1)
        self.zPresetButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.zPresetButton1.setObjectName("zPresetButton1")
        self.gridLayout_7.addWidget(self.zPresetButton1, 4, 3, 1, 1)
        self.xPresetButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.xPresetButton1.setObjectName("xPresetButton1")
        self.gridLayout_7.addWidget(self.xPresetButton1, 4, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 2, 8, 5, 3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.LstagePresetButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.LstagePresetButton1.setObjectName("LstagePresetButton1")
        self.gridLayout_5.addWidget(self.LstagePresetButton1, 2, 2, 1, 1)
        self.currentLStagePositionLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentLStagePositionLabel.setScaledContents(False)
        self.currentLStagePositionLabel.setWordWrap(True)
        self.currentLStagePositionLabel.setObjectName("currentLStagePositionLabel")
        self.gridLayout_5.addWidget(self.currentLStagePositionLabel, 0, 1, 1, 1)
        self.currentLStagePositionText = QtWidgets.QLabel(self.centralwidget)
        self.currentLStagePositionText.setObjectName("currentLStagePositionText")
        self.gridLayout_5.addWidget(self.currentLStagePositionText, 0, 2, 1, 1)
        self.LstagePresetWidget1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LstagePresetWidget1.setDecimals(3)
        self.LstagePresetWidget1.setMaximum(220.0)
        self.LstagePresetWidget1.setSingleStep(0.05)
        self.LstagePresetWidget1.setObjectName("LstagePresetWidget1")
        self.gridLayout_5.addWidget(self.LstagePresetWidget1, 2, 1, 1, 1)
        self.LstagePresetWidget3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LstagePresetWidget3.setDecimals(3)
        self.LstagePresetWidget3.setMaximum(220.0)
        self.LstagePresetWidget3.setSingleStep(0.05)
        self.LstagePresetWidget3.setObjectName("LstagePresetWidget3")
        self.gridLayout_5.addWidget(self.LstagePresetWidget3, 4, 1, 1, 1)
        self.LstagePresetButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.LstagePresetButton2.setObjectName("LstagePresetButton2")
        self.gridLayout_5.addWidget(self.LstagePresetButton2, 3, 2, 1, 1)
        self.LstagePresetButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.LstagePresetButton3.setObjectName("LstagePresetButton3")
        self.gridLayout_5.addWidget(self.LstagePresetButton3, 4, 2, 1, 1)
        self.LstagePresetWidget2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LstagePresetWidget2.setDecimals(3)
        self.LstagePresetWidget2.setMaximum(220.0)
        self.LstagePresetWidget2.setSingleStep(0.05)
        self.LstagePresetWidget2.setObjectName("LstagePresetWidget2")
        self.gridLayout_5.addWidget(self.LstagePresetWidget2, 3, 1, 1, 1)
        self.stageReadRadioNormal = QtWidgets.QRadioButton(self.centralwidget)
        self.stageReadRadioNormal.setChecked(True)
        self.stageReadRadioNormal.setObjectName("stageReadRadioNormal")
        self.gridLayout_5.addWidget(self.stageReadRadioNormal, 1, 1, 1, 1)
        self.stageReadRadioCalibrated = QtWidgets.QRadioButton(self.centralwidget)
        self.stageReadRadioCalibrated.setObjectName("stageReadRadioCalibrated")
        self.gridLayout_5.addWidget(self.stageReadRadioCalibrated, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 2, 6, 8, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fillFractionWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.fillFractionWidget.setDecimals(1)
        self.fillFractionWidget.setMinimum(0.0)
        self.fillFractionWidget.setMaximum(2000.0)
        self.fillFractionWidget.setSingleStep(0.2)
        self.fillFractionWidget.setProperty("value", 1.0)
        self.fillFractionWidget.setObjectName("fillFractionWidget")
        self.gridLayout_4.addWidget(self.fillFractionWidget, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.scansToAverageLabel = QtWidgets.QLabel(self.centralwidget)
        self.scansToAverageLabel.setObjectName("scansToAverageLabel")
        self.gridLayout_4.addWidget(self.scansToAverageLabel, 3, 0, 1, 1)
        self.fillFractionLabel = QtWidgets.QLabel(self.centralwidget)
        self.fillFractionLabel.setObjectName("fillFractionLabel")
        self.gridLayout_4.addWidget(self.fillFractionLabel, 4, 0, 1, 1)
        self.scansToAverage = QtWidgets.QSpinBox(self.centralwidget)
        self.scansToAverage.setMinimum(1)
        self.scansToAverage.setObjectName("scansToAverage")
        self.gridLayout_4.addWidget(self.scansToAverage, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.resolutionWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.resolutionWidget.setDecimals(0)
        self.resolutionWidget.setMinimum(10.0)
        self.resolutionWidget.setMaximum(2000.0)
        self.resolutionWidget.setSingleStep(50.0)
        self.resolutionWidget.setProperty("value", 50.0)
        self.resolutionWidget.setObjectName("resolutionWidget")
        self.gridLayout_4.addWidget(self.resolutionWidget, 2, 1, 1, 1)
        self.dwellTime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dwellTime.setDecimals(0)
        self.dwellTime.setMinimum(1.0)
        self.dwellTime.setProperty("value", 2.0)
        self.dwellTime.setObjectName("dwellTime")
        self.gridLayout_4.addWidget(self.dwellTime, 1, 1, 1, 1)
        self.ZoomLabel = QtWidgets.QLabel(self.centralwidget)
        self.ZoomLabel.setObjectName("ZoomLabel")
        self.gridLayout_4.addWidget(self.ZoomLabel, 0, 0, 1, 1)
        self.zoomWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.zoomWidget.setDecimals(0)
        self.zoomWidget.setMinimum(1.0)
        self.zoomWidget.setMaximum(500.0)
        self.zoomWidget.setProperty("value", 1.0)
        self.zoomWidget.setObjectName("zoomWidget")
        self.gridLayout_4.addWidget(self.zoomWidget, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 5, 0, 8, 3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PMTPreset2 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTPreset2.setObjectName("PMTPreset2")
        self.gridLayout.addWidget(self.PMTPreset2, 3, 3, 1, 1)
        self.PMTLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.PMTLabel1.setObjectName("PMTLabel1")
        self.gridLayout.addWidget(self.PMTLabel1, 1, 2, 1, 1)
        self.PMTLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.PMTLabel3.setObjectName("PMTLabel3")
        self.gridLayout.addWidget(self.PMTLabel3, 1, 4, 1, 1)
        self.pmtInvert1 = QtWidgets.QCheckBox(self.centralwidget)
        self.pmtInvert1.setObjectName("pmtInvert1")
        self.gridLayout.addWidget(self.pmtInvert1, 5, 1, 1, 1)
        self.PMTPreset0 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTPreset0.setObjectName("PMTPreset0")
        self.gridLayout.addWidget(self.PMTPreset0, 3, 1, 1, 1)
        self.PMTSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.PMTSlider3.setMaximum(1000)
        self.PMTSlider3.setOrientation(QtCore.Qt.Vertical)
        self.PMTSlider3.setObjectName("PMTSlider3")
        self.gridLayout.addWidget(self.PMTSlider3, 2, 4, 1, 1)
        self.PMTLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.PMTLabel2.setObjectName("PMTLabel2")
        self.gridLayout.addWidget(self.PMTLabel2, 1, 3, 1, 1)
        self.StokesShutterButton = QtWidgets.QPushButton(self.centralwidget)
        self.StokesShutterButton.setObjectName("StokesShutterButton")
        self.gridLayout.addWidget(self.StokesShutterButton, 4, 0, 1, 1)
        self.PumpShutterButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PumpShutterButton.sizePolicy().hasHeightForWidth())
        self.PumpShutterButton.setSizePolicy(sizePolicy)
        self.PumpShutterButton.setObjectName("PumpShutterButton")
        self.gridLayout.addWidget(self.PumpShutterButton, 3, 0, 1, 1)
        self.PMTPreset1 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTPreset1.setObjectName("PMTPreset1")
        self.gridLayout.addWidget(self.PMTPreset1, 3, 2, 1, 1)
        self.PMTSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.PMTSlider2.setMaximum(1000)
        self.PMTSlider2.setOrientation(QtCore.Qt.Vertical)
        self.PMTSlider2.setObjectName("PMTSlider2")
        self.gridLayout.addWidget(self.PMTSlider2, 2, 3, 1, 1)
        self.pmtInvert4 = QtWidgets.QCheckBox(self.centralwidget)
        self.pmtInvert4.setObjectName("pmtInvert4")
        self.gridLayout.addWidget(self.pmtInvert4, 5, 4, 1, 1)
        self.pmtInvert2 = QtWidgets.QCheckBox(self.centralwidget)
        self.pmtInvert2.setObjectName("pmtInvert2")
        self.gridLayout.addWidget(self.pmtInvert2, 5, 2, 1, 1)
        self.PMTLabel0 = QtWidgets.QLabel(self.centralwidget)
        self.PMTLabel0.setObjectName("PMTLabel0")
        self.gridLayout.addWidget(self.PMTLabel0, 1, 1, 1, 1)
        self.PMTZero3 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTZero3.setObjectName("PMTZero3")
        self.gridLayout.addWidget(self.PMTZero3, 4, 4, 1, 1)
        self.PMTZero0 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTZero0.setObjectName("PMTZero0")
        self.gridLayout.addWidget(self.PMTZero0, 4, 1, 1, 1)
        self.PMTZero1 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTZero1.setObjectName("PMTZero1")
        self.gridLayout.addWidget(self.PMTZero1, 4, 2, 1, 1)
        self.PMTZero2 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTZero2.setObjectName("PMTZero2")
        self.gridLayout.addWidget(self.PMTZero2, 4, 3, 1, 1)
        self.PMTSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.PMTSlider1.setMaximum(1000)
        self.PMTSlider1.setOrientation(QtCore.Qt.Vertical)
        self.PMTSlider1.setObjectName("PMTSlider1")
        self.gridLayout.addWidget(self.PMTSlider1, 2, 2, 1, 1)
        self.PMTSlider0 = QtWidgets.QSlider(self.centralwidget)
        self.PMTSlider0.setMaximum(1000)
        self.PMTSlider0.setOrientation(QtCore.Qt.Vertical)
        self.PMTSlider0.setTickInterval(0)
        self.PMTSlider0.setObjectName("PMTSlider0")
        self.gridLayout.addWidget(self.PMTSlider0, 2, 1, 1, 1)
        self.PMTPreset3 = QtWidgets.QPushButton(self.centralwidget)
        self.PMTPreset3.setObjectName("PMTPreset3")
        self.gridLayout.addWidget(self.PMTPreset3, 3, 4, 1, 1)
        self.pmtInvert3 = QtWidgets.QCheckBox(self.centralwidget)
        self.pmtInvert3.setObjectName("pmtInvert3")
        self.gridLayout.addWidget(self.pmtInvert3, 5, 3, 1, 1)
        self.PMTStatusText = QtWidgets.QLabel(self.centralwidget)
        self.PMTStatusText.setObjectName("PMTStatusText")
        self.gridLayout.addWidget(self.PMTStatusText, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 11, 11, 1)
        Microscoper2017.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Microscoper2017)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAdd_ons = QtWidgets.QMenu(self.menubar)
        self.menuAdd_ons.setObjectName("menuAdd_ons")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuRemote = QtWidgets.QMenu(self.menubar)
        self.menuRemote.setObjectName("menuRemote")
        Microscoper2017.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Microscoper2017)
        self.statusbar.setObjectName("statusbar")
        Microscoper2017.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(Microscoper2017)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Open = QtWidgets.QAction(Microscoper2017)
        self.action_Open.setObjectName("action_Open")
        self.action_About = QtWidgets.QAction(Microscoper2017)
        self.action_About.setObjectName("action_About")
        self.action_setImageLevels = QtWidgets.QAction(Microscoper2017)
        self.action_setImageLevels.setObjectName("action_setImageLevels")
        self.action_Spectrometer = QtWidgets.QAction(Microscoper2017)
        self.action_Spectrometer.setObjectName("action_Spectrometer")
        self.action_Rotation_Stage = QtWidgets.QAction(Microscoper2017)
        self.action_Rotation_Stage.setObjectName("action_Rotation_Stage")
        self.actionBring_all_to_front = QtWidgets.QAction(Microscoper2017)
        self.actionBring_all_to_front.setObjectName("actionBring_all_to_front")
        self.action_Connect = QtWidgets.QAction(Microscoper2017)
        self.action_Connect.setObjectName("action_Connect")
        self.action_Disconnect = QtWidgets.QAction(Microscoper2017)
        self.action_Disconnect.setObjectName("action_Disconnect")
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_Quit)
        self.menuHelp.addAction(self.action_About)
        self.menuSettings.addAction(self.action_setImageLevels)
        self.menuAdd_ons.addAction(self.action_Spectrometer)
        self.menuAdd_ons.addAction(self.action_Rotation_Stage)
        self.menuWindow.addAction(self.actionBring_all_to_front)
        self.menuRemote.addAction(self.action_Connect)
        self.menuRemote.addAction(self.action_Disconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuRemote.menuAction())
        self.menubar.addAction(self.menuAdd_ons.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Microscoper2017)
        QtCore.QMetaObject.connectSlotsByName(Microscoper2017)

    def retranslateUi(self, Microscoper2017):
        _translate = QtCore.QCoreApplication.translate
        Microscoper2017.setWindowTitle(_translate("Microscoper2017", "MainWindow"))
        self.deltaOffsetLabel.setText(_translate("Microscoper2017", "dOffset (V)"))
        self.microcopeOffsetRadio.setText(_translate("Microscoper2017", "XY Stage"))
        self.galvoOffsetRadio.setText(_translate("Microscoper2017", "Galvo"))
        self.upButton.setText(_translate("Microscoper2017", "Up"))
        self.leftButton.setText(_translate("Microscoper2017", "Left"))
        self.downButton.setText(_translate("Microscoper2017", "Down"))
        self.rightButton.setText(_translate("Microscoper2017", "Right"))
        self.label_2.setText(_translate("Microscoper2017", "Directory"))
        self.label.setText(_translate("Microscoper2017", "Filename"))
        self.browseButton.setText(_translate("Microscoper2017", "Browse"))
        self.AcquireButton.setText(_translate("Microscoper2017", "Acquire"))
        self.saveCheckBox.setText(_translate("Microscoper2017", "Save"))
        self.LStageEndLabel.setText(_translate("Microscoper2017", "End (mm)"))
        self.label_5.setText(_translate("Microscoper2017", "Calibration"))
        self.LStageStartLabel.setText(_translate("Microscoper2017", "Start (mm)"))
        self.browseCalibrationButton.setText(_translate("Microscoper2017", "Browse"))
        self.WavenumberText.setText(_translate("Microscoper2017", "0 cm-1"))
        self.LStageMoveLabel.setText(_translate("Microscoper2017", "Speed (mm/s)"))
        self.currentYStagePositionLabel.setText(_translate("Microscoper2017", "Y (mm)"))
        self.currentYStagePositionText.setText(_translate("Microscoper2017", "0"))
        self.currentXStagePositionLabel.setText(_translate("Microscoper2017", "X (mm)"))
        self.currentXStagePositionText.setText(_translate("Microscoper2017", "0"))
        self.currentZStagePositionLabel.setText(_translate("Microscoper2017", "Z (um)"))
        self.currentZStagePositionText.setText(_translate("Microscoper2017", "0"))
        self.yPresetButton1.setText(_translate("Microscoper2017", "Move"))
        self.zPresetButton1.setText(_translate("Microscoper2017", "Move"))
        self.xPresetButton1.setText(_translate("Microscoper2017", "Move"))
        self.LstagePresetButton1.setText(_translate("Microscoper2017", "Move"))
        self.currentLStagePositionLabel.setText(_translate("Microscoper2017", "Current Stage Position (mm)"))
        self.currentLStagePositionText.setText(_translate("Microscoper2017", "0"))
        self.LstagePresetButton2.setText(_translate("Microscoper2017", "Move"))
        self.LstagePresetButton3.setText(_translate("Microscoper2017", "Move"))
        self.stageReadRadioNormal.setText(_translate("Microscoper2017", "Normal"))
        self.stageReadRadioCalibrated.setText(_translate("Microscoper2017", "Calibrated"))
        self.label_3.setText(_translate("Microscoper2017", "Resolution (px)"))
        self.scansToAverageLabel.setText(_translate("Microscoper2017", "Frames to average"))
        self.fillFractionLabel.setText(_translate("Microscoper2017", "Fill fraction"))
        self.label_4.setText(_translate("Microscoper2017", "line dwell time (ms)"))
        self.ZoomLabel.setText(_translate("Microscoper2017", "Zoom"))
        self.PMTPreset2.setText(_translate("Microscoper2017", "700"))
        self.PMTLabel1.setText(_translate("Microscoper2017", "0"))
        self.PMTLabel3.setText(_translate("Microscoper2017", "0"))
        self.pmtInvert1.setText(_translate("Microscoper2017", "Invert"))
        self.PMTPreset0.setText(_translate("Microscoper2017", "700"))
        self.PMTLabel2.setText(_translate("Microscoper2017", "0"))
        self.StokesShutterButton.setText(_translate("Microscoper2017", "Stokes"))
        self.PumpShutterButton.setText(_translate("Microscoper2017", "Pump"))
        self.PMTPreset1.setText(_translate("Microscoper2017", "700"))
        self.pmtInvert4.setText(_translate("Microscoper2017", "Invert"))
        self.pmtInvert2.setText(_translate("Microscoper2017", "Invert"))
        self.PMTLabel0.setText(_translate("Microscoper2017", "0"))
        self.PMTZero3.setText(_translate("Microscoper2017", "Zero"))
        self.PMTZero0.setText(_translate("Microscoper2017", "Zero"))
        self.PMTZero1.setText(_translate("Microscoper2017", "Zero"))
        self.PMTZero2.setText(_translate("Microscoper2017", "Zero"))
        self.PMTPreset3.setText(_translate("Microscoper2017", "700"))
        self.pmtInvert3.setText(_translate("Microscoper2017", "Invert"))
        self.PMTStatusText.setText(_translate("Microscoper2017", "PMT Status : Off"))
        self.menuFile.setTitle(_translate("Microscoper2017", "File"))
        self.menuHelp.setTitle(_translate("Microscoper2017", "Help"))
        self.menuSettings.setTitle(_translate("Microscoper2017", "Settings"))
        self.menuAdd_ons.setTitle(_translate("Microscoper2017", "Add-ons"))
        self.menuWindow.setTitle(_translate("Microscoper2017", "Window"))
        self.menuRemote.setTitle(_translate("Microscoper2017", "Remote"))
        self.action_Quit.setText(_translate("Microscoper2017", "&Quit"))
        self.action_Open.setText(_translate("Microscoper2017", "&Open TIFF"))
        self.action_About.setText(_translate("Microscoper2017", "&About"))
        self.action_setImageLevels.setText(_translate("Microscoper2017", "&Image Levels"))
        self.action_Spectrometer.setText(_translate("Microscoper2017", "&Spectrometer"))
        self.action_Rotation_Stage.setText(_translate("Microscoper2017", "&Rotation Stage"))
        self.actionBring_all_to_front.setText(_translate("Microscoper2017", "Bring all to front"))
        self.action_Connect.setText(_translate("Microscoper2017", "&Connect"))
        self.action_Disconnect.setText(_translate("Microscoper2017", "&Disconnect"))

