# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SSCalibExtract.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SSCalibExtract(object):
    def setupUi(self, SSCalibExtract):
        SSCalibExtract.setObjectName("SSCalibExtract")
        SSCalibExtract.resize(570, 434)
        self.centralwidget = QtWidgets.QWidget(SSCalibExtract)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.upperFrequencyCutOffSpinBoxWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.upperFrequencyCutOffSpinBoxWidget.setMinimum(1.0)
        self.upperFrequencyCutOffSpinBoxWidget.setMaximum(9999.0)
        self.upperFrequencyCutOffSpinBoxWidget.setProperty("value", 4500.0)
        self.upperFrequencyCutOffSpinBoxWidget.setObjectName("upperFrequencyCutOffSpinBoxWidget")
        self.gridLayout_2.addWidget(self.upperFrequencyCutOffSpinBoxWidget, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.executeText = QtWidgets.QLineEdit(self.centralwidget)
        self.executeText.setObjectName("executeText")
        self.horizontalLayout_3.addWidget(self.executeText)
        self.executePushButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.executePushButtonWidget.setObjectName("executePushButtonWidget")
        self.horizontalLayout_3.addWidget(self.executePushButtonWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 5, 0, 1, 3)
        self.guiCanvas = QtWidgets.QGridLayout()
        self.guiCanvas.setObjectName("guiCanvas")
        self.gridLayout_2.addLayout(self.guiCanvas, 4, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveFileButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.saveFileButtonWidget.setObjectName("saveFileButtonWidget")
        self.horizontalLayout_2.addWidget(self.saveFileButtonWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 7, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.undoButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.undoButtonWidget.setObjectName("undoButtonWidget")
        self.gridLayout_2.addWidget(self.undoButtonWidget, 1, 2, 1, 1)
        self.pumpWavelengthSpinBoxWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pumpWavelengthSpinBoxWidget.setMinimum(1.0)
        self.pumpWavelengthSpinBoxWidget.setMaximum(9999.0)
        self.pumpWavelengthSpinBoxWidget.setProperty("value", 800.0)
        self.pumpWavelengthSpinBoxWidget.setObjectName("pumpWavelengthSpinBoxWidget")
        self.gridLayout_2.addWidget(self.pumpWavelengthSpinBoxWidget, 1, 1, 1, 1)
        self.saveFileDefaultButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.saveFileDefaultButtonWidget.setObjectName("saveFileDefaultButtonWidget")
        self.gridLayout_2.addWidget(self.saveFileDefaultButtonWidget, 7, 2, 1, 1)
        self.loadFileButtonWidget = QtWidgets.QPushButton(self.centralwidget)
        self.loadFileButtonWidget.setObjectName("loadFileButtonWidget")
        self.gridLayout_2.addWidget(self.loadFileButtonWidget, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lowerFrequencyCutOffSpinBoxWidget = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lowerFrequencyCutOffSpinBoxWidget.setMinimum(1.0)
        self.lowerFrequencyCutOffSpinBoxWidget.setMaximum(9999.0)
        self.lowerFrequencyCutOffSpinBoxWidget.setProperty("value", 300.0)
        self.lowerFrequencyCutOffSpinBoxWidget.setObjectName("lowerFrequencyCutOffSpinBoxWidget")
        self.gridLayout_2.addWidget(self.lowerFrequencyCutOffSpinBoxWidget, 2, 1, 1, 1)
        self.gridLayout_2.setRowStretch(0, 3)
        SSCalibExtract.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SSCalibExtract)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 21))
        self.menubar.setObjectName("menubar")
        SSCalibExtract.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SSCalibExtract)
        self.statusbar.setObjectName("statusbar")
        SSCalibExtract.setStatusBar(self.statusbar)

        self.retranslateUi(SSCalibExtract)
        QtCore.QMetaObject.connectSlotsByName(SSCalibExtract)

    def retranslateUi(self, SSCalibExtract):
        _translate = QtCore.QCoreApplication.translate
        SSCalibExtract.setWindowTitle(_translate("SSCalibExtract", "MainWindow"))
        self.label_2.setText(_translate("SSCalibExtract", "Upper frequency cutoff"))
        self.executePushButtonWidget.setText(_translate("SSCalibExtract", "Execute"))
        self.saveFileButtonWidget.setText(_translate("SSCalibExtract", "Save calibration"))
        self.label.setText(_translate("SSCalibExtract", "Pump wavelength"))
        self.undoButtonWidget.setText(_translate("SSCalibExtract", "Undo"))
        self.saveFileDefaultButtonWidget.setText(_translate("SSCalibExtract", "Save calibration default"))
        self.loadFileButtonWidget.setText(_translate("SSCalibExtract", "Load file"))
        self.label_3.setText(_translate("SSCalibExtract", "Lower frequency cutoff"))

